dataset:
  data_path: /home/admin_mcn/hungpv/polyps/dataset/BD/5folds
  train_data_path:
    - /home/admin_mcn/hungpv/polyps/dataset/BD/5folds/fold1
    - /home/admin_mcn/hungpv/polyps/dataset/BD/5folds/fold2
    - /home/admin_mcn/hungpv/polyps/dataset/BD/5folds/fold3
    - /home/admin_mcn/hungpv/polyps/dataset/BD/5folds/fold4
  test_data_path:
    - /home/admin_mcn/hungpv/polyps/dataset/BD/test
  val_data_path:
    - /home/admin_mcn/hungpv/polyps/dataset/BD/5folds/fold0

model:
  num_classes: 1
  save_dir: /mnt/data/hungpv/polyps/checkpoint/bd/pvtv2-segformer_v1
  backbone: PVTv2-B3
  head: SegFormerHead
  pretrained: '/mnt/data/hungpv/polyps/pretrained-backbone/pvt_v2_b3.pth'

optimizer:
  name: adam
  lr: 0.0001
  clip: 0.5
  scheduler: cosine_warmup
  num_warmup_epoch: 1
  loss: structure_loss

dev: cuda

train:
  start_from: 0
  save_from: 14
  num_epochs: 15
  num_warmup_epoch: 2
  is_val: True
  size_rates:
    # - 0.75
    - 1
    # - 1.25

  dataloader:
    batchsize: 16
    img_size: 256
    shuffle: True
    num_workers: 2
    pin_memory: True
    drop_last: True

  amp: False
  ddp: False

  augment:
    prob: 1
    Flip_prob: 0.7
    HueSaturationValue_prob: 0.7
    RandomBrightnessContrast_prob: 0.5
    crop_prob: 0.2
    randomrotate90_prob: 0.7
    # elastictransform_prob: 0.7
    # gridistortion_prob: 0.7
    # opticaldistortion_prob: 0.7
    # verticalflip_prob: 0.7
    # horizontalflip_prob: 0.7
    # randomgamma_prob: 0.7
    # CoarseDropout_prob: 0.7
    # RGBShift_prob: 0.7
    # MotionBlur_prob: 0.7
    # MedianBlur_prob: 0.7
    # GaussianBlur_prob: 0.7
    # GaussNoise_prob: 0.7
    # ChannelShuffle_prob: 0.7

test:
  dev: cuda
  csv_save: '/home/admin_mcn/hungpv/polyps/code/bd-segmentation/csv'
  visualize: False
  visualize_dir: '/mnt/data/hungpv/polyps/visualize'
  vis_x: 180
  vis_overwrite: False
  checkpoint_dir: '/mnt/data/hungpv/polyps/checkpoint/bd/pvtv2-segformer_v1/PVTv2-B3-SegFormerHead_best.pth'
  dataloader:
    batchsize: 1
    img_size: 256 
    shuffle: True
    num_workers: 2
    pin_memory: True
    drop_last: True

  augment:

    prob: 1
    Flip_prob: 0
    HueSaturationValue_prob: 0
    RandomBrightnessContrast_prob: 0
    crop_prob: 0
    randomrotate90_prob: 0
    elastictransform_prob: 0
    gridistortion_prob: 0
    opticaldistortion_prob: 0
    verticalflip_prob: 0
    horizontalflip_prob: 0
    randomgamma_prob: 0
    CoarseDropout_prob: 0
    RGBShift_prob: 0
    MotionBlur_prob: 0
    MedianBlur_prob: 0
    GaussianBlur_prob: 0
    GaussNoise_prob: 0
    ChannelShuffle_prob: 0
